# Generated by Django 2.2.2 on 2019-06-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190620_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Book_Name', max_length=100, null=True)),
                ('total_books_taken', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=1)),
                ('issue_take', models.DateTimeField(blank=True, null=True, verbose_name='Issued')),
                ('issue_return', models.DateTimeField(blank=True, null=True, verbose_name='Return')),
            ],
        ),
    ]
